# -*- coding: utf-8 -*-
"""VGG19Labels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLjVmvvaMRxjJPcqxYz2SlkP1k9Uzai6
"""

from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg19 import preprocess_input
from keras.applications.vgg19 import decode_predictions
from keras.applications.vgg19 import VGG19
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive')

model = VGG19()
image = load_img('gdrive/MyDrive/Colab Notebooks/index.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
image = preprocess_input(image)
predict_label = model.predict(image)
labels = decode_predictions(predict_label, top=1000)[0]
names=[y for (x,y,z) in labels]
print(names)